language: node_js
node_js:
  - node

cache:
  directories:
    - "node_modules"

branches:
  only:
    - source

install: yarn
script: yarn build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  target-branch: master
  local-dir: .vuepress/dist
  keep_history: false
  on:
    branch: source